name = "SurrealDB"
uuid = "7b3dffa2-a94d-4703-aaf5-57911c725dc8"
authors = ["Yuri Miyamori"]
version = "0.0.1"

[compat]
julia = "1.6, 1.8"
HTTP = "1.7, 1.8"
JSON = "0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
